kuanblog/blueprints/blog.py
'''
@Author: your name
@Date: 2020-01-30 23:24:27
@LastEditTime : 2020-02-01 12:25:00
@LastEditors: Please set LastEditors
@Description: In User Settings Edit
@FilePath: \11.宽的博客\kuanblog\blueprints\blog.py
'''
# 从flask中导入蓝本类
from flask import Blueprint
from flask import url_for, render_template, request, current_app
from kuanblog.models import Article, Category, Article

# 创建蓝本实例，第一个参数是蓝本名称，第二个传入块的名称
blog_bp = Blueprint("blog", __name__)

@blog_bp.route("/")
def index():
    # 从查询字符串获取当前页数
    page = request.args.get("page", 1, type=int)
    # 从配置中获取每页的数量
    per_page = current_app.config["KUANBLOG_PER_PAGE"]
    # 查询后使用paginate方法，第一个参数传入页数，第二个参数传入每页项目数
    pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page=per_page)
    articles = pagination.items
    return render_template("blog/index.html", pagination=pagination, articles=articles)

@blog_bp.route("/about")
def about():
    return render_template("blog/about.html")

@blog_bp.route("/category/<int:category_id>")
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["KUANBLOG_PER_PAGE"]
    pagination = Article.query.with_parent(category).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, articles=articles)

@blog_bp.route("/article/<int:article_id>")
def show_article(article_id):
    article = Article.query.get_or_404(article_id)
    return render_template("blog/article.html", article=article)

    

kuanblog/templates/blog/_articles.html
<!--
 * @Author: your name
 * @Date: 2020-01-31 17:09:30
 * @LastEditTime : 2020-02-01 12:05:51
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \10.宽的博客\kuanblog\templates\blog\_articles.html
 -->
{% if category %}
<div class="page-header">
    <h1>Category: {{ category.name }}</h1>
    <p class="text-muted">{{ category.articles|length }} articles</p>
</div>
{% endif %}
{% if articles %}
{% for article in articles %}
    <h3 class="text-primary"><a href="{{ url_for('blog.show_article', article_id=article.id) }}", article_id=article.id>{{ article.title }}</a></h3>
    <p>
        {{ article.body|striptags|truncate }}
        <small><a href="{{ url_for('blog.show_article', article_id=article.id) }}">Read More</a></small>
    </p>
    <small>
        Comments: <a>{{ article.comments|length }}</a>&nbsp;&nbsp;

        Category: <a href="{{ url_for('blog.show_category', category_id=article.category.id) }}">{{ article.category.name }}</a>
        <span class="float-right">{{ article.timestamp }}</span>


    </small>
    {% if not loop.last %}
        <hr>
    {% endif %}
{% endfor %}
{% else %}
<div class="tip">
<h5>No Articles yet</h5>
</div>
{% endif %}

kuanblog/templates/blog/_mainarticle.html
<!--
 * @Author: your name
 * @Date: 2020-02-01 15:58:03
 * @LastEditTime : 2020-02-01 16:02:47
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \10.宽的博客\kuanblog\templates\blog\_mainarticle.html
 -->

{% block mycss %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/markdown.css') }}">
{% endblock %}

{{ article.body | safe }}

kuanblog/templates/blog/_sidebar.html
<!--
 * @Author: your name
 * @Date: 2020-01-31 15:23:03
 * @LastEditTime : 2020-02-01 12:03:17
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \10.宽的博客\kuanblog\templates\blog\_sidebar.html
 -->
<div class="card">
    <div class="card-header">
        <div class="text-center">文章类别</div>
    </div>
    <ul class="list-group">
        {% for category in categories %}
        <li class="list-group-item">

            <a href="{{ url_for('blog.show_category', category_id=category.id) }}">{{ category.name }}</a>

            <span class="badge badge-pill badge-secondary float-right">{{ category.articles|length }}</span>
        </li>
        {% endfor %}
    </ul>
</div>

kuanblog/templates/blog/about.html
<!--
 * @Author: your name
 * @Date: 2020-01-31 15:39:30
 * @LastEditTime : 2020-01-31 15:40:18
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \10.宽的博客\kuanblog\templates\blog\about.html
 -->
{% extends 'base.html' %}

{% block content %}
<h1>Hiro_Huang的自我介绍</h1>
{% endblock content %}

kuanblog/templates/blog/article.html
<!--
 * @Author: your name
 * @Date: 2020-01-31 17:12:39
 * @LastEditTime : 2020-02-01 16:01:23
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \10.宽的博客\kuanblog\templates\blog\article.html
 -->

{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-9 col-sm-8">
        <div class="page-header">
            <h1>{{ article.title }}</h1>
            <small>

                Category: <a href="{{ url_for('blog.show_category', category_id=article.category.id) }}">{{ article.category.name }}</a><br>

                Date: {{ article.timestamp }}
            </small>
            <div>{% include 'blog/_mainarticle.html' %}</div>
        </div>
         <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#shareTab">分享</button>
        <div class="modal fade" id="shareTab">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">文章地址</h4>
                        <button class="close" data-dismiss="modal">%times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" class="form-control" value="{{ url_for('.show_article', article_id=article.id, _external=True) }}" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if categories %}
    <div class="col-lg-3 col-sm-4">
        <!-- 侧面栏 -->
        {% include "blog/_sidebar.html" %}
    </div>
    {% endif %}
</div>
{% endblock content %}

kuanblog/templates/blog/category.html
<!--
 * @Author: your name
 * @Date: 2020-01-31 10:13:34
 * @LastEditTime : 2020-01-31 17:11:12
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \11.宽的博客\kuanblog\templates\blog\index.html
 -->
 {% extends 'base.html' %}

 {% block content %}
 <div class="row">
     <div class="col-lg-9 col-sm-8">
        {% include "blog/_articles.html" %}
     </div>
     {% if categories %}
     <div class="col-lg-3 col-sm-4">
         <!-- 侧面栏 -->
         {% include "blog/_sidebar.html" %}
     </div>
     {% endif %}
 </div>
 {% endblock content %}

 

kuanblog/templates/blog/index.html
<!--
 * @Author: your name
 * @Date: 2020-01-31 10:13:34
 * @LastEditTime : 2020-02-01 11:57:52
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \11.宽的博客\kuanblog\templates\blog\index.html
 -->
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block content %}
<div class="row">
    <div class="col-lg-9 col-sm-8">
        {% include "blog/_articles.html" %}
    </div>
    {% if categories %}
    <div class="col-lg-3 col-sm-4">
        {% include "blog/_sidebar.html" %}
    </div>
    {% endif %}
</div>
{{ render_pagination(pagination) }}
{% endblock content %}