kuanblog/blueprints/admin.py
'''
@Author: your name
@Date: 2020-01-31 11:42:58
@LastEditTime : 2020-02-01 12:27:58
@LastEditors  : Please set LastEditors
@Description: In User Settings Edit
@FilePath: \11.宽的博客\kuanblog\blueprints\admin.py
'''
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from kuanblog.forms import LoginForm, ArticleForm, CategoryForm
from flask_login import login_user, current_user, logout_user, login_required
from kuanblog.models import Admin, Article, Category
from kuanblog.utils import redirect_back
from kuanblog.extensions import db


admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash("欢迎登录", "success")
                return redirect_back() # 返回上一个页面
            else:
                flash("密码或用户名错误", "warning")
        else:
            flash("没有设置管理员账号", "warning")
    return render_template('admin/login.html', form=form)

@admin_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("已登出用户", "info")
    return redirect_back()
    
@admin_bp.route('/article/manage')
@login_required
def manage_article():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config['KUANBLOG_MANAGE_PER_PAGE']
    pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('admin/manage_article.html', pagination=pagination, articles=articles)


@admin_bp.route('/article/<int:article_id>/delete')
@login_required
def delete_article(article_id):
    article = Article.query.get_or_404(article_id)
    db.session.delete(article)
    db.session.commit()
    flash("已删除文章", "success")
    return redirect_back()

@admin_bp.route('/article/<int:article_id>/edit', methods=["GET", "POST"])
@login_required
def edit_article(article_id):
    form = ArticleForm()
    article = Article.query.get_or_404(article_id)
    if form.validate_on_submit():
        article.title = form.title.data
        article.body = form.body.data
        article.category = Category.query.get(form.category.data)
        db.session.commit()
        flash("已完成文章的修改", "success")
        return redirect(url_for('admin.manage_article'))
    form.title.data = article.title
    form.body.data = article.body
    # 这个要注意下，我们只用了id就渲染出了对应的名称
    form.category.data = article.category_id
    return render_template('admin/edit_article.html', form=form)

@admin_bp.route('article/new', methods=["GET","POST"])
@login_required
def new_article():
    form = ArticleForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        article = Article(title=title, body=body, category=category)
        db.session.add(article)
        db.session.commit()
        flash('已新建一篇文章', 'success')
        return redirect(url_for(".manage_article"))
    return render_template('admin/new_article.html', form=form)

@admin_bp.route('/category/manage')
@login_required
def manage_category():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config['KUANBLOG_MANAGE_PER_PAGE']
    pagination = Category.query.order_by(Category.name.asc()).paginate(page, per_page)
    categories = pagination.items
    return render_template('admin/manage_category.html', pagination=pagination, categories=categories)

@admin_bp.route('category/new', methods=["GET","POST"])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('已创建新类别', 'success')
        return redirect(url_for(".manage_category"))
    return render_template('admin/new_category.html', form=form)

@admin_bp.route("/category/<int:category_id>/delete")
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash("已删除类别", "success")
    return redirect_back()

kuanblog/blueprints/blog.py
'''
@Author: your name
@Date: 2020-01-30 23:24:27
@LastEditTime : 2020-02-01 12:25:00
@LastEditors: Please set LastEditors
@Description: In User Settings Edit
@FilePath: \11.宽的博客\kuanblog\blueprints\blog.py
'''
# 从flask中导入蓝本类
from flask import Blueprint
from flask import url_for, render_template, request, current_app
from kuanblog.models import Article, Category, Article

# 创建蓝本实例，第一个参数是蓝本名称，第二个传入块的名称
blog_bp = Blueprint("blog", __name__)

@blog_bp.route("/")
def index():
    # 从查询字符串获取当前页数
    page = request.args.get("page", 1, type=int)
    # 从配置中获取每页的数量
    per_page = current_app.config["KUANBLOG_PER_PAGE"]
    # 查询后使用paginate方法，第一个参数传入页数，第二个参数传入每页项目数
    pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page=per_page)
    articles = pagination.items
    return render_template("blog/index.html", pagination=pagination, articles=articles)

@blog_bp.route("/about")
def about():
    return render_template("blog/about.html")

@blog_bp.route("/category/<int:category_id>")
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["KUANBLOG_PER_PAGE"]
    pagination = Article.query.with_parent(category).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, articles=articles)

@blog_bp.route("/article/<int:article_id>")
def show_article(article_id):
    article = Article.query.get_or_404(article_id)
    return render_template("blog/article.html", article=article)

    

kuanblog/templates/base.html
<!--
 * @Author: your name
 * @Date: 2020-01-30 22:06:41
 * @LastEditTime: 2020-03-10 23:59:12
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \00.博客练习\blog.html
 -->
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Audit Bucket</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block mycss %}
    {% endblock %}
</head>
<style>
</style>
<body>
    <!-- 导航栏 -->
    <!-- navbar：导航条；navbar-expand-sm：设置屏幕堆叠； bg-light：背景色； navbar-light：字体色；fixed-top：置顶 -->
    <nav class="navbar navbar-expand-sm bg-light navbar-light fixed-top">
        <!-- container：修正导航宽度； justify-content-start：设置元素排版 -->
        <div class="container justify-content-start">
            <!-- 建立到首页的链接 -->
            <a href="{{ url_for('blog.index' )}}" class="navbar-brand"><img src="{{ url_for('static', filename='images/auditbucketicon.png') }}" height="30">  Home</a>
            <button class="navbar-toggler ml-auto" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <!-- <li class="nav-item active">
                        <a class="nav-link" href="#">Excel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.about') }}">About Me</a>
                    </li> -->
                    {{ render_nav_item('blog.about', 'About me')}}
                    <!-- 使用bootstrap模板渲染导航 -->
                    <!-- {{ render_nav_item('blog.index', 'Home') }} -->
                </ul>                  
                <div class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                    <div class="dropdown">
                        <button type="button" class="btn dropdown-toggle" role="button" data-toggle="dropdown" data-target>新增<span class="caret"></span></button>
                        <div class="dropdown-menu">
                            <a href="{{ url_for('admin.new_article') }}" class="dropdown-item">新增文章</a>
                            <a href="{{ url_for('admin.new_category') }}" class='dropdown-item'>新增类别</a>
                        </div>
                    </div>
                    <div class="dropdown">
                        <button type="button" class="btn dropdown-toggle" role="button" data-toggle="dropdown" data-target>管理<span class="caret"></span></button>
                        <div class="dropdown-menu">
                            <a href="{{ url_for('admin.manage_article') }}" class="dropdown-item">文章管理</a>
                            <a href="{{ url_for('admin.manage_category') }}" class='dropdown-item'>类别管理</a>
                        </div>
                    </div>

                    <a class="nav-link" href="{{ url_for('admin.logout', next=request.full_path) }}">登出</a>
                    {% else %}
                    <!-- <a class="nav-link" href="{{ url_for('admin.login', next=request.full_path) }}">登录</a> -->
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    
    <!-- 导航栏 -->
    <!-- 巨幕 -->
    {% block jumbotron %}
    <div class="jumbotron">
        <div class="container">
            <h1>Audit Bucket <small></small></h1>
            
            <p class="lead">这里只有干货!!!</p>

        </div>
    </div>
    {% endblock jumbotron %}
    <!-- 巨幕 -->

    <main class="container">

        <!-- 消息部分 -->
        {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
        {% endfor %}
        <!-- 内容区域 -->
        {% block content %}{% endblock content %}
        <footer>
            <small>AuditBucket©2020 | 黄宽慎的官方网站 | 备案号：<a href="http://beian.miit.gov.cn/" target="_blank">闽ICP备20002019号</a></small>
        </footer>
    </main>
    
</body>
<script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% block scripts %}
{% endblock scripts %}
</html>